# This is my CI pipeline
name: terraform-azure-function-ci

# trigger pipeline when code is push
on:
  push:
    branches:
    - main

jobs:
  build:
    # Github has both ubuntu-lastest or windows-latest. In this scenario, can use both, but Ubuntu is the best practice
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v4
    - name: Terraform Init
      run: terraform init
    - name: Terraform Format Checkout
      run: terraform fmt -check
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Plan
      run: terraform plan